#!/bin/sh
### BEGIN INIT INFO
# Provides:          infusion-pump
# Required-Start:    $network $remote_fs $syslog mosquitto
# Required-Stop:     $network $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Inicia o controle da Bomba de Infusão
### END INIT INFO

case "$1" in
  start)
    echo "Iniciando Bomba de Infusão..."
    # ATENÇÃO: Caminho atualizado para onde a receita instalou (/usr/bin/infusion-pump-app)
    start-stop-daemon --start --background --make-pidfile --pidfile /var/run/infusion-pump.pid \
        --exec /usr/bin/python3 -- /usr/bin/infusion-pump-app >> /var/log/infusion-pump.log 2>&1
    ;;
  stop)
    echo "Parando Bomba de Infusão..."
    start-stop-daemon --stop --pidfile /var/run/infusion-pump.pid
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "Uso: /etc/init.d/infusion-pump {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
